common:
    macros:
        - TARGET_K64F
        - TARGET_M4
        - TARGET_Freescale
        - __CORTEX_M4
        - ARM_MATH_CM4
        - __MBED__=1
        - CPU_MK64FN1M0VMD12
        - FSL_RTOS_MBED
tool_specific:
    gcc_arm:
        misc:
            cxx_flags:
            - -mfpu=fpv4-sp-d16
            - -mfloat-abi=softfp
